config/routes.rb
Rails.application.routes.draw do
  get '/', to: "welcome#home", as: "home"

  #Pet routes
  get '/pets', to: "pets#index", as: "pets"
  get '/pets/new', to: "pets#new", as: "new_pet"
  get '/pets/:id', to: "pets#show", as: "pet"
  patch '/pets/:id', to: "pets#update"
  get '/pets/:id/edit', to: "pets#edit", as: "edit_pet"
  post '/pets', to: "pets#create"
  delete '/pets/:id/delete', to: "pets#delete"
  
  #Owner routes
  get '/owners', to: "owners#index", as: "owners"
  get '/owners/new', to: "owners#new", as: "new_owner"
  get "/owners/two", to: "owners#two"
  get '/owners/:id', to: "owners#show", as: "owner"
  patch '/owners/:id', to: "owners#update"
  get '/owners/:id/edit', to: "owners#edit", as: "edit_owner"
  post '/owners', to: "owners#create"
  delete '/owners/:id/delete', to: "owners#delete"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_one_attached :image
    has_many :pets, :dependent => :destroy
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  
  def index
    @owners = Owner.all
  end

  def new
    @owner = Owner.new
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def two
    @owners = []
    Owner.all.each do |owner_instance|
      if owner_instance.pets.size >= 2
        @owners << owner_instance.first_name
      end
    end
  end

  def create
    @owner = Owner.create(owner_params)
    redirect_to owner_path(@owner)
  end

  def update
    @owner = Owner.find(params[:id])
    @owner.update(owner_params)
    redirect_to owner_path(@owner)
  end

  def delete
    @owner = Owner.find(params[:id])
    @owner.destroy
    redirect_to owners_path
  end

  private
  
  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :age, :email, :image)
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  
  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
    @owners = Owner.all
    @species = ["Cat", "Dog", "Bird"]
  end

  def edit
    @pet = Pet.find(params[:id])
    @owners = Owner.all
    @species = ["Cat", "Dog", "Bird"]
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.create(pet_params)
    redirect_to pet_path(@pet)
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path
  end

  def delete
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :species, :owner_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
        render :index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/edit.html.erb
<h1>Edit <%=@owner.first_name%> <%=@owner.last_name%></h1>

<%=form_for @owner do |f| %>
<%= f.label :first_name%>
<%= f.text_field :first_name %><br>
<%= f.label :last_name%>
<%= f.text_field :last_name %><br>
<%= f.label :age%>
<%= f.number_field :age%><br>
<%= f.label :email%>
<%= f.email_field :email %><br>
<%= f.submit %>
<% end %>

app/views/owners/index.html.erb
<h1>All Owners</h1>

<%@owners.each do |owner|%>
<li><%=link_to "#{owner.first_name}",  owner_path(owner) %></li>
<%end%>
<br>
<%= button_to "Add an Owner", new_owner_path, method: :get%>
<br>
<%= button_to "Home Page", home_path, method: :get%>

app/views/owners/new.html.erb
<h1>Create a new Owner</h1>

<%=form_for @owner do |f| %>
<%= f.label :first_name%>
<%= f.text_field :first_name %><br>
<%= f.label :last_name%>
<%= f.text_field :last_name %><br>
<%= f.label :age%>
<%= f.number_field :age%><br>
<%= f.label :email%>
<%= f.email_field :email %><br>
<%= f.label :image %>
<%= f.file_field :image %>
<%= f.submit %>
<% end %>

app/views/owners/show.html.erb
<h1>Hello <%=@owner.first_name%></h1>
<!-- <p><%=@owner.first_name%> <%=@owner.last_name%></p> -->
<%= image_tag(@owner.image, style:'width:10%')%>
<p>You are <%=@owner.age%> years old</p>
<p>Your email address is: <%=@owner.email%></p>
<ol>
    <th>Your Pets are:</th>
    <%@owner.pets.each do |pet|%>
    <li><%=link_to "#{pet.name}", pet_path(pet)%></li>
    <%end%>
</ol>
<%= button_to "Edit your account", edit_owner_path, method: :get%>
<%= button_to "Delete your account", "/owners/#{@owner.id}/delete", method: :delete%>
<%= button_to "Return to Owners page", owners_path, method: "get" %>

app/views/owners/two.html.erb
<%@owners.each do |owner|%>
    <ul><%=owner%></ul>
<%end%>

<%= button_to "Return to Owners page", owners_path, method: "get" %>

app/views/pets/edit.html.erb
<h1>Edit <%=@pet.name%></h1>

<%=form_for @pet do |f| %>
<%= f.label :name%>
<%= f.text_field :name %> <br>
<%= f.label :species%>
<%= f.collection_select :species, @species, :to_s, :to_s%><br>
<%= f.label :owner%>
<%= f.collection_select :owner_id, @owners, :id, :first_name%><br>
<%= f.submit %>
<% end %>

app/views/pets/index.html.erb
<h1>All Pets</h1>
<p>Find me in app/views/pets/index.html.erb</p>

<%@pets.each do |pet|%>
<li><%=link_to "#{pet.name}",  pet_path(pet) %></li>
<%end%>
<br>
<%= button_to "Add a Pet", new_pet_path, method: :get%>
<br>
<%= button_to "Home Page", home_path, method: :get%>

app/views/pets/new.html.erb
<h1>Create a new Pet</h1>

<%=form_for @pet do |f| %>
<%= f.label :name%>
<%= f.text_field :name %> <br>
<%= f.label :species%>
<%= f.collection_select :species, @species, :to_s, :to_s%><br>
<%= f.label :owner%>
<%= f.collection_select :owner_id, @owners, :id, :first_name%><br>
<%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<h1><%=@pet.name%></h1>
<p><%=@pet.name%> is a <%=@pet.species%></p>
<p><%=@pet.name%>'s owner is <%=link_to "#{@pet.owner.first_name}", owner_path(@pet.owner), method: :get%></p>
<%= button_to "Edit #{@pet.name}", edit_pet_path, method: :get%>
<%= button_to "Delete #{@pet.name}", "/pets/#{@pet.id}/delete", method: :delete%> <br>
<%= button_to "Return to Pets page", pets_path, method: "get" %>

app/views/welcome/home.html.erb
<h1>Welcome To This Magnificent Application</h1>
<%= button_to "Pets page", pets_path, method: "get" %>
<%= button_to "Owners page", owners_path, method: "get" %>

app/views/welcome/index.html.erb
<h1>Welcome To This Magnificent Application</h1>
<%= button_to "Pets page", pets_path, method: "get" %>
<%= button_to "Owners page", owners_path, method: "get" %>